# Generated by Django 5.2.8 on 2026-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=10, unique=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('passenger_count', models.IntegerField()),
                ('journey_active', models.BooleanField(default=True)),
            ],
        ),
    ]
