# Generated by Django 5.2.8 on 2026-02-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainpassenger',
            old_name='mobile_number',
            new_name='booking_mobile',
        ),
    ]
