# Generated by Django 5.2.8 on 2026-03-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('session_id', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
